apiVersion: v1
kind: Service
metadata:
  name: optimism-verifier
  namespace: bnbchain
  labels:
    app: optimism-verifier
spec:
  ports:
    - name: optimism-verifier
      port: 8545
      protocol: TCP
      targetPort: 8545
  selector:
    app: optimism-verifier
  type: ClusterIP
